/**
 * ZATCA Sandbox — Minimal Raw cURL-style Test
 * 
 * Reads the CSR generated by the SDK and sends it with proper base64 cleanup.
 * Also tries with/without \r to debug the "Invalid Request" response.
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

const csrPem = fs.readFileSync(path.join(require('os').tmpdir(), 'sandbox_csr.csr'), 'utf8');

// Strip PEM headers and ALL whitespace (including \r\n)
const csrBase64 = csrPem
    .replace(/-----BEGIN CERTIFICATE REQUEST-----/g, '')
    .replace(/-----END CERTIFICATE REQUEST-----/g, '')
    .replace(/[\r\n\s]/g, '')
    .trim();

console.log('CSR base64 length:', csrBase64.length);
console.log('CSR base64 (first 80):', csrBase64.substring(0, 80));
console.log('Has \\r?', csrBase64.includes('\r'));
console.log('Has \\n?', csrBase64.includes('\n'));
console.log();

const body = JSON.stringify({ csr: csrBase64 });
console.log('Request body length:', body.length);
console.log('Request body:', body.substring(0, 120), '...\n');

const options = {
    hostname: 'gw-fatoora.zatca.gov.sa',
    port: 443,
    path: '/e-invoicing/developer-portal/compliance',
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'Accept-Version': 'V2',
        'Accept-Language': 'en',
        'OTP': '123456',
        'Content-Length': Buffer.byteLength(body),
    },
};

console.log('Sending request to:', `https://${options.hostname}${options.path}`);
console.log('Headers:', JSON.stringify(options.headers, null, 2));
console.log();

const req = https.request(options, (res) => {
    let data = '';
    res.on('data', chunk => data += chunk);
    res.on('end', () => {
        console.log('HTTP Status:', res.statusCode);
        console.log('Response Headers:', JSON.stringify(res.headers, null, 2));
        console.log('Response Body:', data);
        
        // Try to parse JSON
        try {
            const parsed = JSON.parse(data);
            console.log('\nParsed JSON:', JSON.stringify(parsed, null, 2));
        } catch {
            console.log('\n(Response is not JSON)');
        }
    });
});

req.on('error', (err) => {
    console.error('Request error:', err.message);
});

req.write(body);
req.end();
