csr.common.name=1-SmartTouch|2-POS-9013|3-311167090900003
csr.serial.number=1-SmartTouch|2-POS-9013|3-311167090900003
csr.organization.identifier=311167090900003
csr.organization.unit.name=Head Office
csr.organization.name=مؤسسة ابراهيم سالم بن عوده البلوي للمقاولات العامة
csr.country.name=SA
csr.invoice.type=1100
csr.location.address=Riyadh
csr.industry.business.category=Retail