const crypto = require('crypto');
const fs = require('fs');

try {
    const pk = fs.readFileSync('temp_private_key.pem', 'utf8'); // This is the one generated by openssl
    const signer = crypto.createSign('SHA256');
    signer.update('test');
    signer.sign(pk);
    console.log("Success!");
} catch (e) {
    console.log(e.stack || e);
}
