/**
 * reset_zatca_keys.cjs  —  Task 4: Clear stale secp256k1 keys from zatca_device
 *
 * This script wipes all cryptographic state (private key, certificates, chain PIH)
 * from the zatca_device table so that the next onboarding run will store a clean
 * prime256v1 key generated by the fixed generateCSR() path.
 *
 * Run ONCE after deploying the zatca_phase2_impl.cjs fix, BEFORE re-onboarding.
 *
 * Usage:
 *   node reset_zatca_keys.cjs
 *   -- or (to target pos.db instead) --
 *   node reset_zatca_keys.cjs pos.db
 *
 * NOTE: better-sqlite3 must be compiled for the Node.js version you are running.
 * If you see an ABI error, first run:
 *   npx electron-rebuild -f -w better-sqlite3
 * and then invoke this script via:
 *   npx electron . --run-reset  (if wired in main.cjs)
 */

'use strict';

const path = require('path');
const fs   = require('fs');

// ── Locate database ──────────────────────────────────────────────────────────
const dbFileName = process.argv[2] || 'pos_data.db';
const DB_PATH    = path.isAbsolute(dbFileName)
    ? dbFileName
    : path.join(__dirname, dbFileName);

if (!fs.existsSync(DB_PATH)) {
    console.error(`\n❌  Database not found at: ${DB_PATH}`);
    console.error('    Pass the correct filename as the first argument.\n');
    process.exit(1);
}

// ── Load better-sqlite3 ──────────────────────────────────────────────────────
let Database;
try {
    Database = require('better-sqlite3');
} catch (err) {
    console.error('\n❌  Failed to load better-sqlite3:', err.message);
    console.error('    ABI mismatch? Run: npx electron-rebuild -f -w better-sqlite3\n');
    process.exit(1);
}

const db = new Database(DB_PATH, { verbose: null });

// ── Confirm table exists ─────────────────────────────────────────────────────
const tableExists = db.prepare(
    "SELECT name FROM sqlite_master WHERE type='table' AND name='zatca_device'"
).get();

if (!tableExists) {
    console.error('\n❌  Table "zatca_device" does not exist in', DB_PATH);
    console.error('    Check the DB file or schema name.\n');
    process.exit(1);
}

// ── Show BEFORE state ────────────────────────────────────────────────────────
console.log('\n══════════════════════════════════════════════════════════════');
console.log('  ZATCA Key Reset — clearing stale secp256k1 device credentials');
console.log('══════════════════════════════════════════════════════════════\n');

const before = db.prepare('SELECT id, private_key_pem IS NOT NULL AS has_key, compliance_cert_pem IS NOT NULL AS has_comp_cert, production_cert_pem IS NOT NULL AS has_prod_cert, last_pih FROM zatca_device').all();
console.log('BEFORE (row count: ' + before.length + '):');
console.table(before);

// ── Wipe all ZATCA key/cert/chain state in one transaction ───────────────────
const resetKeys = db.transaction(() => {
    const result = db.prepare(`
        UPDATE zatca_device
        SET
            private_key_pem          = NULL,
            public_key_pem           = NULL,
            compliance_csid          = NULL,
            compliance_token         = NULL,
            compliance_secret        = NULL,
            compliance_cert_pem      = NULL,
            production_csid          = NULL,
            production_token         = NULL,
            production_secret        = NULL,
            production_cert_pem      = NULL,
            last_pih                 = NULL,
            last_icv                 = 0,
            onboarding_status        = 'pending'
    `).run();
    return result.changes;
});

let changed;
try {
    changed = resetKeys();
} catch (err) {
    // Some columns may not exist in every schema revision — retry with minimal set
    console.warn('[WARN] Full reset failed, retrying with minimal column set:', err.message);
    const resetMinimal = db.transaction(() => {
        // Only touch columns that definitely exist in every schema version
        const cols = db.prepare('PRAGMA table_info(zatca_device)').all().map(c => c.name);
        const toNull = [
            'private_key_pem', 'public_key_pem',
            'compliance_cert_pem', 'production_cert_pem',
            'compliance_token', 'compliance_secret',
            'production_token', 'production_secret',
            'last_pih',
        ].filter(c => cols.includes(c));

        const setClauses = toNull.map(c => `${c} = NULL`).join(', ');
        const extras = [];
        if (cols.includes('last_icv'))         extras.push('last_icv = 0');
        if (cols.includes('onboarding_status')) extras.push("onboarding_status = 'pending'");

        const fullSet = [...toNull.map(c => `${c} = NULL`), ...extras].join(', ');
        return db.prepare(`UPDATE zatca_device SET ${fullSet}`).run().changes;
    });
    changed = resetMinimal();
}

// ── Show AFTER state ─────────────────────────────────────────────────────────
console.log(`\n✅  Reset ${changed} row(s) in zatca_device.\n`);

const after = db.prepare('SELECT id, private_key_pem IS NOT NULL AS has_key, compliance_cert_pem IS NOT NULL AS has_comp_cert, production_cert_pem IS NOT NULL AS has_prod_cert, last_pih FROM zatca_device').all();
console.log('AFTER:');
console.table(after);

db.close();

console.log('\n══════════════════════════════════════════════════════════════');
console.log('  Done. All stale keys cleared. Re-run onboarding to enroll');
console.log('  a fresh prime256v1 device certificate.');
console.log('══════════════════════════════════════════════════════════════\n');
